
@startuml Services

class Connection { }
class Session { }
class Room { }

package SessionManagementService {
    class DefaultSessionManager implements SessionManager{}
    class MockSessionManager implements SessionManager  {}
}
package RoomManagementService {

    class DefaultRoomManager implements RoomManager{}
    class MockRoomManager implements RoomManager{}

}

@enduml