@startuml SigningProcess

actor User

entity Connection
entity Session

database SessionService
database AuthenticationService

User -> Connection : connect(token)
Connection -> AuthenticationService: authenticate(creds)
Connection <- AuthenticationService: Token

Connection -> SessionService: getSession(Token)
SessionService -> Session: create
SessionService -> Connection: session
activate Session

User -> Connection: command
Connection -> Session: ForwardCommand

@enduml