[package]
name = "server2"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.2.0"
warp = "0.2.5"
xactor = "0.7.7"
env_logger = "0.7.1"
log = "0.4.11"
dotenv = "0.15.0"
color-backtrace = "0.4.2"
async-compat = "0.1.3"
futures = "0.3.5"
async-trait = "0.1.40"
anyhow = "1.0.32"

[[bin]]
name = "server2"
path = "./src/main.rs"
