[package]
name = "server2"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.2.0"
warp = "0.2.5"
xactor = "0.7.7"

log = "0.4"
env_logger = "0.7"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"]}
dotenv = "0.15"
config = "0.10"
uuid = { version = "0.8", features = ["serde", "v4"] }

color-backtrace = "0.4"
async-compat = "0.1"
futures = "0.3"
async-trait = "0.1"
anyhow = "1.0"

signaler-protocol = { path = "../protocol" }

[[bin]]
name = "server2"
path = "./src/main.rs"
