[package]
name = "signaler"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
edition = "2018"

[dependencies]
actix-web = "3.1"
actix-web-actors = "3.0"
actix-files = "0.4"
actix = "0.10"
log = "0.4"
env_logger = "0.7"
build_timestamp = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"]}
dotenv = "0.15"
config = "0.10"

chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
color-backtrace = "0.4"

signaler-protocol = { path = "../protocol" }
