[package]
name = "signalizer"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
log = "0.4"
env_logger = "0.6"
build_timestamp = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"]}

uuid = { version = "0.7.1", features = ["serde"] }

[dependencies.actix]
version = "0.7"
##features = ["signal"]